# Generated by Django 4.1.6 on 2023-02-13 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ibd_visits', '0001_initial'),
        ('ibd_website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalvisit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalvisit',
            name='visit_term',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='ibd_visits.doctorvisit'),
        ),
        migrations.AddField(
            model_name='doctorvisit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibd_website.doctor'),
        ),
        migrations.AddField(
            model_name='doctorvisit',
            name='visit_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibd_visits.visitterm'),
        ),
    ]
